export const SET_GENRE_FILTER = 'SET_GENRE_FILTER';
export const SET_AUTHOR_GENDER_FILTER = 'SET_AUTHOR_GENDER_FILTER';
export const SET_ORDER_BY_BOOK_NAME = 'SET_ORDER_BY_BOOK_NAME';
export const SET_ORDER_BY_AUTHOR_NAME = 'SET_ORDER_BY_AUTHOR_NAME';
export const SCROLL_POSITION_CHANGE = 'SCROLL_POSITION_CHANGE';
export const SET_AVAILABLE_BOOKS = 'SET_AVAILABLE_BOOKS';
export const SET_BOOKS = 'SET_BOOKS';
export const SET_LOADING = 'SET_LOADING';
